// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AAvatar: typeof import('ant-design-vue/es')['Avatar']
    AInputSearch: typeof import('ant-design-vue/es')['InputSearch']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader']
    ALayoutSider: typeof import('ant-design-vue/es')['LayoutSider']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    ASubMenu: typeof import('ant-design-vue/es')['SubMenu']
    ATable: typeof import('ant-design-vue/es')['Table']
    DiffWord: typeof import('./src/components/revise-record/diff-word.vue')['default']
    Empty: typeof import('./src/components/Editor/src/Empty.vue')['default']
    HomeContent: typeof import('./src/components/Home/src/homeContent.vue')['default']
    HomeMenu: typeof import('./src/components/Home/src/homeMenu.vue')['default']
    Loading: typeof import('./src/components/global/loading/index.vue')['default']
    Main: typeof import('./src/components/Editor/src/main.vue')['default']
    Mention: typeof import('./src/components/Editor/src/mention.vue')['default']
    RecordItem: typeof import('./src/components/revise-record/record-item.vue')['default']
    ReviseRecord: typeof import('./src/components/revise-record/index.vue')['default']
  }
}

export { }
